GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjEzODdlMjFiYWI2MDk1YTE2MzViMzUiLCJuYW1lIjoiTnVydWwgUmFobWFuZGEiLCJ1c2VybmFtZSI6Im51cnVsLnJhaG1hbmRhIiwiZW1haWwiOiJudXJ1bHJhaG1hbmRhQGdtYWlsLmNvbSIsImlhdCI6MTcxMjY0MDk1NCwiZXhwIjoxNzEyNjQwOTY5fQ.Pll0MPg0-mxTRH3kogSJIncTatNTUMMAmcr8qmDaFlM

###
GET http://localhost:5000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjEzODdlMjFiYWI2MDk1YTE2MzViMzUiLCJuYW1lIjoiTnVydWwgUmFobWFuZGEiLCJ1c2VybmFtZSI6Im51cnVsLnJhaG1hbmRhIiwiZW1haWwiOiJudXJ1bHJhaG1hbmRhQGdtYWlsLmNvbSIsImlhdCI6MTcxMjY0MDk1NCwiZXhwIjoxNzEyNjQwOTY5fQ.Pll0MPg0-mxTRH3kogSJIncTatNTUMMAmcr8qmDaFlM

###
GET http://localhost:5000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjEzODdlMjFiYWI2MDk1YTE2MzViMzUiLCJuYW1lIjoiTnVydWwgUmFobWFuZGEiLCJ1c2VybmFtZSI6Im51cnVsLnJhaG1hbmRhIiwiZW1haWwiOiJudXJ1bHJhaG1hbmRhQGdtYWlsLmNvbSIsImlhdCI6MTcxMjY0MDk1NCwiZXhwIjoxNzEyNjQwOTY5fQ.Pll0MPg0-mxTRH3kogSJIncTatNTUMMAmcr8qmDaFlM

###
POST http://localhost:5000/register
Content-Type: application/json

{
    "firstName": "Nihayatul",
    "lastName": "Fathiyah",
    "email": "ayaaa@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "nurulrahmanda@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout